### ISSUE TITLE
help with setting up hyperledger fabric explorer

### ISSUE THREAD

**Issue by arya09021998** [huynhanh475/cologne-project#50]
can you please help with setting up the explorer 
thankyou...

**Comment by huynhanh475** [comment]
Hi @arya09021998 , I don't really get what you mean by hyperledger fabric explorer. But from what I just got from the internet, it means that you want to integrate Hyperledger Explorer to the this project, right? If it is, then afraid I can't help with it, because we use React to build the frontend webapp instead.

From what I researched, you will need to clone the [blockchain-explorer](https://github.com/hyperledger-labs/blockchain-explorer) repo, then modify the file **blockchain-explorer/app/platform/fabric/connection-profile/first-network.json** to fit this food supply chain network config. You can find our network config in directory **network/config** or see how API is configured to connect to the network in **api/fabric**.

You may want to check out this tutorial: https://eplt.medium.com/5-minutes-to-install-hyperledger-explorer-with-fabric-on-ubuntu-18-04-digitalocean-9b100d0cfd7d

Hope it help! :>

**Comment by arya09021998** [comment]
thankyou for your suggestion...! I will try your given solution.
